CANVAS_WIDTH = 60
CANVAS_HEIGHT = 20
NUMBER_OF_CARDS = CANVAS_HEIGHT * CANVAS_WIDTH
NUMBER_OF_COMBAT_CARDS = 30
NUMBER_OF_LETTER_CARDS = 10
NUMBER_OF_TASK_CARDS = 60
NUMBER_OF_QUIZ_CARDS = 20

CARD_DEFINITION_PATH = "legionarek/assets"
