CANVAS_WIDTH = 20
CANVAS_HEIGHT = 6
NUMBER_OF_CARDS = CANVAS_HEIGHT * CANVAS_WIDTH
NUMBER_OF_COMBAT_CARDS = 30
NUMBER_OF_LETTER_CARDS = 10
NUMBER_OF_TASK_CARDS = 60
NUMBER_OF_QUIZ_CARDS = 20
NUMBER_OF_LIVES = 3
MIN_NUMBER_OF_PLAYERS = 2
MAX_NUMBER_OF_PLAYERS = 4

CARD_DEFINITION_PATH = "legionarek/assets"
